language: node_js

node_js:
- node

services:
- mysql

sudo: required #

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client

before_install:
  - mysql -e "CREATE DATABASE arduino;"
  - mysql -e "create user 'arduinoSlave'@'localhost' identified with mysql_native_password by '123456'; "
  - mysql -e "grant all privileges on arduino.* to 'arduinoSlave'@'localhost';"


after_success: 
- npm run lh -- --perf=85  https://meteo-server.herokuapp.com/
