language: node_js

node_js:
- node

services:
- mysql

sudo: required #

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client

before_install:
  - mysql_upgrade
  - mysql -e "CREATE DATABASE arduino;"
  - mysql -e "create user 'arduinoSlave'@'localhost' identified with mysql_native_password by '123456'; "
  - mysql -e "grant all privileges on arduino.* to 'arduinoSlave'@'localhost';"

jobs:
  include:
    - stage: Vulnerabilities
      script: npm run inspect:vulnerabilities
    - stage: Eslint
      script: npm run inspect:lint
    - stage: Tests
      script: npm run inspect:mocha 


after_success: 
- npm run lh -- --perf=85  https://meteo-server.herokuapp.com/
