version: '3.1'
services:

  meteo-server:
    build:
      dockerfile: Dockerfile
      context: .
    command: node app.js
    environment:
      DB_HOST: db:3306
      DB_PASSWORD: n%FFodEK9Oso9@0U
    ports:
    - 5060:5060 # [порт компьютера]:[порт контейнера]
    depends_on:
      - db    


  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      DB_DATABASE: "arduino"
      DB_USERNAME: "arduinoSlave"
      DB_PASSWORD: "n%FFodEK9Oso9@0U"
    volumes:
      - /var/lib/mysql
    ports:
      - "3307:3306"
