version: '3.1'
services:

  meteo-server:
    build:
      dockerfile: Dockerfile
      context: .
    #command: ["./wait-for-it.sh", "db:3306", "--", "node", "app.js"]
    ports:
    - 5060:5060 # [порт компьютера]:[порт контейнера]
    depends_on:
      - db    

  db:
    build: 
      dockerfile: DockerfileDB
      context: .
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: foo
      MYSQL_DATABASE: "arduino"
      MYSQL_USERNAME: "arduinoSlave"
      MYSQL_PASSWORD: "123456" # возможно он ломается из-за проостого пароля
    ports:
      - "3307:3306"
