version: '3.1'
services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD
      - DB_DATABASE
      - DB_USERNAME
      - DB_PASSWORD
  meteo-server:
    build:
      dockerfile: Dockerfile
      context: .
    command: node app.js
    volumes:
      - "./src:/home/node/app/src"
    environment:
      - DB_HOST=localhost
      - DB_NAME=${DATABASE}
      - DB_USER=${USERNAME}
      - DB_PASSWORD=${PASSWORD}
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:app.test.localhost.tv"
    depends_on:
      - db
